src/objects/CM_Project__c.object
<CustomObject>
    <description>Cloud Mentor Project Object to track detailed information about a Project</description>
    <fields>
        <fullName>DeadLine__c</fullName>
        <label>DeadLine</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <formula>DeadLine__c - Kickoff__c + 1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Kickoff__c</fullName>
        <label>Kickoff</label>
        <type>Date</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CM_Task__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Predecessor_Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Predecessor Task</label>
        <referenceTo>CM_Task__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectName__c</fullName>
        <label>Project</label>
        <referenceTo>CM_Project__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Dates__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Task_Progress__c</fullName>
        <label>Task Progress</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Task_Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resolved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Close</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>end_date__c</fullName>
        <formula>TEXT(DAY(Due_Date__c ))+&quot;-&quot; +TEXT(MONTH(Due_Date__c ))+&quot;-&quot; +TEXT(YEAR(Due_Date__c ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>End Date Formula</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>start_date__c</fullName>
        <formula>TEXT(DAY(Start_Dates__c))+&quot;-&quot; +TEXT(MONTH(Start_Dates__c))+&quot;-&quot; +TEXT(YEAR(Start_Dates__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Start Date Formula</label>
        <type>Text</type>
    </fields>
    <label>Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/GanttChartv2_Ctrl.cls
public class GanttChartv2_Ctrl {
    
    public GanttChartv2_Ctrl(){
        
    }
    
    @RemoteAction
    public static projectInfo getProjectInfo(Id projectId){
        
        
        system.debug('projectId '+projectId);
        projectInfo info = new projectInfo();
        List<data> tasks = new List<data>();
        
        for(CM_Project__c proj : [Select Id,Name,Duration__c,Kickoff__c,DeadLine__c,
                                  (Select Id,Name,start_date__c,end_date__c,Task_Stage__c,Assigned_To__c,Predecessor_Task__c,Task_Progress__c from Tasks__r) 
                                  from CM_Project__c where Id =:projectId])
        {
            
            data pk = new data();
            pk.id = proj.Id;
            pk.text = proj.Name;
            pk.start_date = proj.Kickoff__c.day()+'-'+proj.Kickoff__c.month()+'-'+proj.Kickoff__c.year();
            pk.end_date = proj.DeadLine__c.day()+'-'+proj.DeadLine__c.month()+'-'+proj.DeadLine__c.year(); 
            pk.duration = String.valueOf(proj.Duration__c);                    
            pk.open = true;
            
            system.debug('start_date '+pk.start_date);                               
            
            tasks.add(pk);                         
            
            //Get the Task-Details                          
            for(CM_Task__c task : proj.Tasks__r){
                
                data tk = new data();

                tk.staus = task.Task_Stage__c;
                tk.id = task.Id;
                tk.text = task.Name;
				tk.progress = task.Task_Progress__c!=null?task.Task_Progress__c/100 :null;
                if(task.Predecessor_Task__c != null){
                    tk.parent = task.Predecessor_Task__c;
                }else{
                    tk.parent = proj.Id;
                }
                tk.assignedTo = task.Assigned_To__c!=null?string.valueOf(task.Assigned_To__c):null;
                tk.status = task.Task_Stage__c;
                tk.start_date = task.start_date__c;
                tk.end_date = task.end_date__c;
                tk.open = true;
                tasks.add(tk);
            }            
        }
        //Get the Link Details
        List<link> links = new List<link>();
        
        info.data = tasks;
        info.link = links;
        
        system.debug(info);
        return info;
    }
    
    @RemoteAction
    public static List<Contact> getContacts(){
        return [Select Id,Name from Contact limit 10];
    }
    
    @RemoteAction
    public static Id upsertTask(String projectId, data newData,Boolean isNew){
        Id taskId = null;
        system.debug('newData '+newData);
        
        CM_Task__c newTask = new CM_Task__c();
        
        Id parentId = (Id)newData.parent;
        
        String parentObj = parentId.getSObjectType().getDescribe().getName();
        system.debug('parentObj '+parentObj);
        
        if(parentObj == 'CM_Task__c'){
            newTask.Predecessor_Task__c = parentId;
        }

        if(!isNew){
            system.debug('isNew '+isNew+newData.id);
            newTask.Id = newData.id;           
        }else{
            newTask.ProjectName__c = projectId; 
        }
       
        newTask.Name = newData.text;
        newTask.Start_Dates__c = Date.parse(newData.start_date);
       
        newTask.Task_Stage__c = newData.status;
        newTask.Due_Date__c = Date.parse(newData.end_date);
        newTask.Assigned_To__c = newData.users[0];
        
        system.debug('newTask '+newTask);
        upsert newTask;
        
        return newTask.Id;
    }
    
     @RemoteAction
    public static Boolean deleteTask(String taskId){
        Delete [Select Id from CM_Task__c where id =: taskId];
        return true;
    }
    
    @RemoteAction
    public static Id udpateTask(updateTask task){
        
        CM_Task__c upTask = new CM_Task__c();
        upTask.id = task.id;
        upTask.Start_Dates__c = Date.parse(task.start_date);
        upTask.Due_Date__c = Date.parse(task.end_date);
       
        update upTask;
        return upTask.id;
    }
    //Task_Progress__c
	
    @RemoteAction
    public static Id udpateProgressTask(String taskId, Decimal progress){
        
        CM_Task__c upTask = new CM_Task__c();
        upTask.id = taskId;
        upTask.Task_Progress__c = progress*100;
        update upTask;
        
        return upTask.id;
    }
    
    public class updateTask{
        public string id;
        public string start_date;
        public string end_date;
    }
    
    
    public class projectInfo{
        public List<data> data;
        public List<link> link;
    }
    
    public class data{
        public string id;
        public string text;
        public string start_date;
        public string end_date;
        public string duration;
        public string status;
        public string parent;
        public string assignedTo;
        public string staus;
        public Decimal progress;
        public Boolean open;
        public String[] users;
        public String priority;
    }
    
    public class link{
        public string id;
        public string source;
        public string target;
        public string type;
    }
    
}