src/objects/CM_Project__c.object
<CustomObject>
    <description>Cloud Mentor Project Object to track detailed information about a Project</description>
    <fields>
        <fullName>Project_Balance_Hours__c</fullName>
        <formula>Total_Hours_Budget__c -  Task_Estimated_Hours__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Balance Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Task_Estimated_Hours__c</fullName>
        <label>Total Task Estimated Hours</label>
        <summarizedField>CM_Task__c.Estimated_Hours__c</summarizedField>
        <summaryForeignKey>CM_Task__c.ProjectName__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Hours_Budget__c</fullName>
        <label>Total Hours Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ChartController.cls
public class ChartController {
    
    public Integer BudgetedHours{get;set;}
    public Integer estimatedHours{get;set;}
      
    public ChartController(){
        
        BudgetedHours = 0;
        estimatedHours = 0;

		CM_Project__c projectValue = [SELECT Total_Hours_Budget__c,Project_Balance_Hours__c,Task_Estimated_Hours__c from CM_Project__c limit 1];
		BudgetedHours = Integer.valueOf(projectValue.Total_Hours_Budget__c);
		estimatedHours = Integer.valueOf(projectValue.Task_Estimated_Hours__c);
    }
}