src/objects/CM_Project__c.object
<CustomObject>
    <description>Cloud Mentor Project Object to track detailed information about a Project</description>
    <fields>
        <fullName>DeadLine__c</fullName>
        <label>DeadLine</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Kickoff__c</fullName>
        <label>Kickoff</label>
        <type>Date</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CM_Task__c.object
<CustomObject>
    <fields>
        <fullName>Blocked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Blocked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Overall_Status__c</fullName>
        <formula>if ( Complete__c == true, &apos;Complete&apos;,
if ( and( Days_Late_Formula__c &gt; 0, Blocked__c ),
if(Len( Text(Task_Stage__c))&gt;0 , &apos;Late &amp; Blocked &apos; &amp; Text(Task_Stage__c), &apos;Late &amp; Blocked&apos;),
if (Days_Late_Formula__c &gt; 0, 
if(Len( Text(Task_Stage__c))&gt;0, &apos;Late &apos; &amp; text(Task_Stage__c), &apos;Late&apos;),
if(Blocked__c == true, 
if(Len( Text(Task_Stage__c))&gt;0, &apos;Blocked &apos; &amp; text(Task_Stage__c), &apos;Blocked&apos;), 
if(Len( Text(Task_Stage__c))&gt;0, &apos;Open &apos; &amp; Text(Task_Stage__c), &apos;Open&apos;) 
))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Overall Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectName__c</fullName>
        <label>Project</label>
        <referenceTo>CM_Project__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Dates__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Task_Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resolved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Close</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>text__c</fullName>
        <formula>ProjectName__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>text</label>
        <type>Text</type>
    </fields>
    <label>Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ganttChart.cls
public class ganttChart {
  
  public CM_Project__c thisProject;
  public List<CM_Task__c> milestones;
  
  public String projectId;

  public ganttChart(ApexPages.Standardcontroller std)
  {
    projectId = std.getId();
    
    thisProject = [select Id, Kickoff__c, DeadLine__c from CM_Project__c where Id = :projectId];
    
    milestones = [Select id,text__c,Name,Start_Dates__c,Due_Date__c,Task_Stage__c,Overall_Status__c From CM_Task__c Where ProjectName__c=:projectId];
    
  }
  
  public String getMilestoneData()
  {
    String milestoneData = '';
    Integer counter = 0;
    
    String draftData = '';
    String activeData = '';
    String completeData = '';
    String cancelData = '';
    String holdData = '';
    
    for (CM_Task__c m : milestones)
    {
      counter++;
      Integer daysBetween = 2*m.Start_Dates__c.daysBetween(m.Due_Date__c);

      if(m.Overall_Status__c== 'Open')
      {
        draftData += daysBetween;
        activeData += '0';
        completeData += '0';
        cancelData += '0';
        holdData += '0';
      }      
      else if(m.Overall_Status__c== 'Open None')
      {
        draftData += '0';
        activeData += daysBetween;
        completeData += '0';
        cancelData += '0';
        holdData += '0';
      }
      else if(m.Overall_Status__c== 'Complete')
      {
        draftData += '0';
        activeData += '0';
        completeData += daysBetween;
        cancelData += '0';
        holdData += '0';
      }
      else if(m.Overall_Status__c== 'Late')
      {
        draftData += '0';
        activeData += '0';
        completeData += '0';
        cancelData += daysBetween;
        holdData += '0';
      }
      else if(m.Overall_Status__c== 'Blocked__c ')
      {
        draftData += '0';
        activeData += '0';
        completeData += '0';
        cancelData += '0';
        holdData += daysBetween;
      }
      
      if(counter != milestones.size())
      {
          draftData += ',';
          activeData += ',';
          completeData += ',';
          cancelData += ',';
          holdData += ',';
      }
    }
    
    milestoneData = draftData + '|' + activeData + '|' + completeData + '|' + cancelData + '|' + holdData;
    
    return milestoneData;
  }
  
  public String getWhiteData()
  {
    String whiteData = '';
    Integer counter = 0;
    
    for (CM_Task__c m : milestones)
    {
      counter++;
      Integer whiteSpace = 2*thisProject.Kickoff__c.daysBetween(m.Start_Dates__c);
      whiteData += whitespace;
      
      if(counter != milestones.size())
      {
        whiteData += ',';
      }
    }
    
    return whiteData;
  }

  public String getProjectDateRange()
  {
    String dateString = '|';
    Integer projectDays = thisProject.Kickoff__c.daysBetween(thisProject.DeadLine__c );
    Integer interval = projectDays / 10;
    
    Date tempDate = thisProject.Kickoff__c;
    
    for(Integer x = 1; x <= 10; x++)
    {
      dateString += tempDate.month() + '/' + tempDate.day() + '|';
      tempDate = tempDate.addDays(interval);
    }
    
    dateString += thisProject.DeadLine__c.month() + '/' + thisProject.DeadLine__c.day() + '|';
    
    return dateString;
  }
  
  public String getMilestoneNames()
  {
    String milestoneNames = '|';
    
    for(Integer back = milestones.size() - 1; back >= 0; back--)
    {
      milestoneNames += milestones.get(back).Name + '|';  
    }
    
    return milestoneNames;
  }
}