src/objects/CM_Project__c.object
<CustomObject>
    <description>Cloud Mentor Project Object to track detailed information about a Project</description>
    <fields>
        <fullName>Duration__c</fullName>
        <formula>DeadLine__c - Kickoff__c + 1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CM_Task__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectName__c</fullName>
        <label>Project</label>
        <referenceTo>CM_Project__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Task_Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resolved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Close</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>color__c</fullName>
        <formula>IF( Overall_Status__c=&apos;Late In Progress&apos;,&apos;red&apos;,&apos;green&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>color</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>end_date__c</fullName>
        <formula>TEXT(DAY(Due_Date__c ))+&quot;-&quot; +TEXT(MONTH(Due_Date__c ))+&quot;-&quot; +TEXT(YEAR(Due_Date__c ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>End Date Formula</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>progress__c</fullName>
        <formula>Task_Completion__c  / 100</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>progress</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>start_date__c</fullName>
        <formula>TEXT(DAY(Start_Dates__c))+&quot;-&quot; +TEXT(MONTH(Start_Dates__c))+&quot;-&quot; +TEXT(YEAR(Start_Dates__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Start Date Formula</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>text__c</fullName>
        <formula>ProjectName__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>text</label>
        <type>Text</type>
    </fields>
    <label>Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ProjectRecods.cls
public with sharing class ProjectRecods {

    public String str1 {get;set;}
    public String str2 {get;set;}
    Public String str4 {get;set;}
    public String scaleUnit{get;set;}
    public String id;
    public ProjectRecods (){
         
          id = ApexPages.currentPage().getParameters().get('id');
          setScaleUnit();   
          
          List<CM_Task__c> taskList= [Select id,text__c,Name,start_date__c,end_date__c,Task_Stage__c,Assigned_To__r.Name,color__c,progress__c From CM_Task__c Where ProjectName__c=:id];
          String str1  = JSON.serialize(taskList);
          str2  = str1.remove('__c');
          str4 = '{"data":'+str2+','+'"links":[{"id":"10","source":"11","target":"1","type":"1"}]}';
         
       
      }    
      
      Public PageReference  retProject(){
      
          PageReference pageRef = new PageReference('/'+id);
          pageRef.setRedirect(true);

          return pageRef ;
      
      }
      
      public void setScaleUnit(){
          
          CM_Project__c proj = [select id,Duration__c from CM_Project__c where id=:id];
         
          if(proj.Duration__c==1){
              scaleUnit  ='day'; 
          }else if(proj.Duration__c>1 && proj.Duration__c<=7){
              scaleUnit  ='week'; 
          }else if(proj.Duration__c>7 && proj.Duration__c<=31){
              scaleUnit  ='month'; 
          }else if(proj.Duration__c>31 && proj.Duration__c<=90){
              scaleUnit  ='quarter'; 
          }else if(proj.Duration__c>90 && proj.Duration__c<=366){
              scaleUnit  ='year'; 
          }
      }
    
    }